name: Deploy

on:
  push:
    branches:
      - main

jobs:
  - name: "Deploy to production"
  uses: appleboy/ssh-action@master
  with:
    username: ${{ secrets.SSH_USERNAME }}
    host: ${{ secrets.SSH_HOST }}
    key: ${{ secrets.SSH_KEY }}
    port: ${{ secrets.SSH_PORT }}
    script: |
      cd /var/www/node-server
      sudo git pull
      yarn
      pm2 restart hello.papacastor.fr