name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/node-server
            sudo git pull
            yarn
            pm2 restart hello.papacastor.fr